cfehome/src/cfehome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView
from restaurant.views import Restaurantlistview, RestaurantDetailView, RestaurantCreateView



from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name ='home.html'), name= "home"),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^restaurant/', include("restaurant.urls", namespace="restaurant")),
    url('^accounts/', admin.site.urls),
    url(r'^items/', include("menus.urls", namespace="menus")),
    url(r'^u/', include("profiles.urls", namespace="profiles")),
#    url(r'^restaurant/create/$', RestaurantCreateView.as_view(), name= "restaurant-create"),
#    url(r'^restaurant/create/$', restaurant_createview),
#    url(r'^restaurant/(?P<slug>\w+)/$', Restaurantlistview.as_view()),
#    url(r'^restaurant/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name ="/restaurant-detail/"),
#    url(r'^restaurant/italijanska/$', Italijanskarestaurantlistview.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name ='about.html'), name= "about"),
    url(r'^contact/$', TemplateView.as_view(template_name ='contact.html'), name= "contact"),
]

cfehome/src/menus/urls.py
from django.conf.urls import url
from .views import ItemCreateView, ItemDetailView, ItemListView, ItemUpdateView

urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(), name= "create"),
#    url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name ="detail"),
    url(r'^$', ItemListView.as_view(), name= "list"),

]

cfehome/src/restaurant/urls.py
from django.conf.urls import url

from .views import Restaurantlistview, RestaurantDetailView, RestaurantCreateView,RestaurantUpdateView, RestoranLocationList
from django.views.generic import TemplateView
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [

    url(r'^create/$', RestaurantCreateView.as_view(), name= "create"),
#    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name ="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name="detail"),
    url(r'^$', Restaurantlistview.as_view(), name= "list"),
    url(r'api/$', RestoranLocationList.as_view(), name="api"),
]

cfehome/src/restaurant/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_category

# Create your models here.
User = settings.AUTH_USER_MODEL
class RestaurantLocation(models.Model):
    owner =          models.ForeignKey(User)
    name =          models.CharField(max_length=120)
    location =      models.CharField(max_length=120, null=True, blank=True)
    category =      models.CharField(max_length=120, null=True, blank=True, validators=[validate_category])
    timestamp=      models.DateTimeField(auto_now_add=True)
    update =        models.DateTimeField(auto_now=True)
    slug =          models.SlugField(null=True, blank=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('restaurant:detail', kwargs={"slug":self.slug})
    @property
    def title(self):
        return self.name
    #pozdrav
def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
pre_save.connect(rl_pre_save_receiver, sender= RestaurantLocation)

cfehome/src/restaurant/forms.py
from django import forms
from .models import  RestaurantLocation
from  .validators import validate_category

class RestorauntCreateForm(forms.Form):
    name =          forms.CharField()
    location =      forms.CharField(required=False)
    category =      forms.CharField(required=False)

class RestaurantLocationCreateForm(forms.ModelForm):
    #category =      forms.CharField(required=False, validators=[validate_category])
    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
            'slug'
        ]

cfehome/src/restaurant/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from .models import RestaurantLocation
from .forms import RestorauntCreateForm, RestaurantLocationCreateForm
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import RestaurantLocationSerializer

'''@login_required(login_url="/login/")
def restaurant_createview(request):
    form = RestaurantLocationCreateForm(request.POST or None)
    errors = None
    if form.is_valid():
        if request.user.is_authenticated():
            instance = form.save(commit= False)
            instance.owner = request.user
            instance.save()
            return HttpResponseRedirect("/restaurant/")
        else:
            return HttpResponseRedirect("/login/")
    if form.errors:
        errors = form.errors

    template_name = 'restaurant/form.html'
    contex = {"form":form}
    return render(request, template_name, contex)





def restaurantlistview(request):
    template_name = "restaurant/restaurantlocation_list.html"
    query_set = RestaurantLocation.objects.all()
    contex ={
        "object_list" : query_set
    }
    return render(request, template_name, contex)
'''
class Restaurantlistview(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner = self.request.user)

class RestaurantDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner = self.request.user)
    def get_context_data(self, **kwargs):
        context = super(RestaurantDetailView, self).get_context_data(**kwargs)
        return context

class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForm
    login_url = '/login/'
    template_name = 'form.html'
    success_url = '/restaurant/'

    def get_context_data(self, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(**kwargs)
        context['title']= 'Add restaurant'
        return context


    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForm
    login_url = '/login/'
    template_name = 'restaurant/detail-update.html'
#    success_url = '/restaurant/'

    def get_context_data(self, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(**kwargs)
        name = self.get_object().name
        context['title'] = 'Update{}'.format(name)
        return context

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)
class RestoranLocationList(APIView):
    def get(self, request):
        restaurant = RestaurantLocation.objects.all()
        serializer = RestaurantLocationSerializer(restaurant, many=True)
        return Response(serializer.data)
    def post(self):
        pass


            









#    return HttpResponse(html_)
# pozdrav

cfehome/src/restaurant/templates/restaurant/detail-update.html
{% extends "base.html"%}

{%block head_title%}{{ form.instance.title}}| Restaurant |{{ block.super }}{%endblock head_title%}
{% block content%}
<h1> {{ form.instance.title}}</h1> <small> {{ form.instance.location }}</small>
<p>{{ form.instance.timestamp }} Updated {{form.instance.update|timesince}} ago</p>
<hr>
<h3>Make changes</h3>
{% include "snippets/form_snippet.html" with form=form %}

{% endblock content%}


<!--<{input type="text" name="name" placeholder = "Your title"><br>
    <input type="text" name="location" placeholder = "Locatio"><br>
    <input type="text" name="category" placeholder = "Category"><br>-->

cfehome/src/restaurant/templates/restaurant/form.html
{% extends "base.html"%}

{%block head_title%}Forms |{{ block.super }}{%endblock head_title%}
{% block content%}
<form method="post"> {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Save</button>
</form>
{% endblock content%}


<!--<input type="text" name="name" placeholder = "Your title"><br>
    <input type="text" name="location" placeholder = "Locatio"><br>
    <input type="text" name="category" placeholder = "Category"><br>-->

cfehome/src/restaurant/templates/restaurant/restaurant_list.html
{% extends "base.html"%}

{%block head_title%}Restaurant |{{ block.super }}{%endblock head_title%}
{% block content%}
<h1>Restaurant list</h1>
<ul>
    {% for obj in object_list %}
    <li>
        {{ obj }}
    </li>
    {% endfor %}
</ul>
{% endblock content%}

cfehome/src/restaurant/templates/restaurant/restaurantlocation_detail.html
{% extends "base.html"%}

{%block head_title%}Restaurant |{{ block.super }}{%endblock head_title%}
{% block content%}
<h1> {{ object.title}}</h1> <small> {{ object.location }}</small>
<p>{{ object.timestamp }} Updated {{object.update|timesince}} ago</p>
{% endblock content%}

cfehome/src/restaurant/templates/restaurant/restaurantlocation_list.html
{% extends "base.html"%}

{%block head_title%}Restaurant |{{ block.super }}{%endblock head_title%}
{% block content%}
<h1>My restorants<small><a href="{% url "restaurant:create" %}">Add</a></small></h1>
<ul>
    {% for obj in object_list %}
    <li>
        <a href="{{obj.get_absolute_url}}">{{ obj }}></a><br>
        {{ obj.name }} {{ obj.location }} {{ obj.timestamp }}
    </li>

    {% empty %}
    <li><a href="{% url "restaurant:create" %}"> Add one</a></li>
    {% endfor %}
</ul>
{% endblock content%}