cfehome/src/cfehome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView
from restaurant.views import Restaurantlistview, RestaurantDetailView, RestaurantCreateView



from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name ='home.html'), name= "home"),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^restaurant/', include("restaurant.urls", namespace="restaurant")),
    url('^accounts/', admin.site.urls),
    url(r'^items/', include("menus.urls", namespace="menus")),
    url(r'^u/', include("profiles.urls", namespace="profiles")),
#    url(r'^restaurant/create/$', RestaurantCreateView.as_view(), name= "restaurant-create"),
#    url(r'^restaurant/create/$', restaurant_createview),
#    url(r'^restaurant/(?P<slug>\w+)/$', Restaurantlistview.as_view()),
#    url(r'^restaurant/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name ="/restaurant-detail/"),
#    url(r'^restaurant/italijanska/$', Italijanskarestaurantlistview.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name ='about.html'), name= "about"),
    url(r'^contact/$', TemplateView.as_view(template_name ='contact.html'), name= "contact"),
]

cfehome/src/menus/urls.py
from django.conf.urls import url
from .views import ItemCreateView, ItemDetailView, ItemListView, ItemUpdateView

urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(), name= "create"),
#    url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name ="detail"),
    url(r'^$', ItemListView.as_view(), name= "list"),

]

cfehome/src/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

cfehome/src/templates/snippets/form_snippet.html
<form method="post"> {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Save</button>
</form>

cfehome/src/templates/snippets/js.html
<script src="http://code.jquery.com/jquery-3.2.1.min.js" ></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

cfehome/src/templates/snippets/nav.html
<div class="container">
<h1>Moupicky.com</h1>
<a href='{% url "home"%}'>Home</a>
{% if request.user.is_authenticated%}
{% if form.instance.name %}
<h1>{{ form.instance.name }}<a href='{% url "restaurant:list"%}'>restaurant</a></h1>
{%endif%}<a href='{% url "menus:list"%}'>Menus items</a>

    {% endif%}
</div>

cfehome/src/templates/snippets/sidebar.html
<ul>
    <li>Item 1.</li>
    <li>Item 2.</li>


</ul>