cfehome/src/menus/urls.py
from django.conf.urls import url
from .views import ItemCreateView, ItemDetailView, ItemListView, ItemUpdateView

urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(), name= "create"),
#    url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name ="detail"),
    url(r'^$', ItemListView.as_view(), name= "list"),

]

cfehome/src/profiles/urls.py
from .views import ProfilesDetailView
from django.conf.urls import url, include


urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfilesDetailView.as_view(), name= "detail"),

]

cfehome/src/menus/models.py
from django.db import models
from django.conf import settings
from restaurant.models import RestaurantLocation
from django.core.urlresolvers import reverse


class Item(models.Model):
    #assosiation
    user =      models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant =models.ForeignKey(RestaurantLocation)
    #real item staf
    name =      models.CharField(max_length=120)
    contents =  models.TextField(help_text= "Separate by comma")
    excludes = models.TextField(blank=True, null= True,help_text="Separate by comma")
    public =    models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta():
        ordering = ["-update","-timestamp"]
    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={"pk":self.pk})
    def get_contents(self):
        return self.contents.split(",")
    def get_excludes(self):
        return self.excludes.split(",")




# Create your models here.

cfehome/src/profiles/models.py
from django.db import models

# Create your models here.

cfehome/src/profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.http import Http404
from django.contrib.auth import get_user_model
from restaurant.models import RestaurantLocation

User = get_user_model()
class ProfilesDetailView(DetailView):
    template_name = 'profiles/user.html'
    def get_object(self):
        user_name = self.kwargs.get("username")
        if user_name is None:
            raise Http404
        return get_object_or_404(User, username__iexact=user_name, is_active =True)
    def get_context_data(self, *args, **kwargs):
        context = super(ProfilesDetailView, self).get_context_data(*args, **kwargs)
        qs = RestaurantLocation.objects.filter(owner = self.get_object())
        if qs.exists:
            context['locations'] = qs
        return context


# Create your views here.

cfehome/src/profiles/templates/profiles/user.html
{% extends "base.html"%}

{%block head_title%}{{ user.username }} |{{ block.super }}{% endblock head_title %}
{% block content%}

<h1>{{ user.username }}</h1>
<hr>
{%if user.item_set.all.exists %}
{%if locations %}
{% for rest in locations %}
    <div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">
            <h4>{{ rest.title }}</h4>
            <p>{{ rest.location }} | {{ rest.category }}
            </p>
        <ul>
            {% for item in rest.item_set.all %}
            <li style="margin-bottom:15px">{{ item.name }}<br>
                {% for ing in item.get_contents %}
                <span class = "badge badge-default">{{ ing }}</span>,
                {% endfor%}
            </li>

            </li>
            {% endfor %}
        </ul>
        </div>
    </div>
    </div>
{% endfor %}
{% else %}
<p class = 'lead'>No items found</p>
{%endif%}
{%endif%}
{% endblock %}