cfehome/src/cfehome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView
from restaurant.views import Restaurantlistview, RestaurantDetailView, RestaurantCreateView



from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name ='home.html'), name= "home"),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^restaurant/', include("restaurant.urls", namespace="restaurant")),
    url('^accounts/', admin.site.urls),
    url(r'^items/', include("menus.urls", namespace="menus")),
    url(r'^u/', include("profiles.urls", namespace="profiles")),
#    url(r'^restaurant/create/$', RestaurantCreateView.as_view(), name= "restaurant-create"),
#    url(r'^restaurant/create/$', restaurant_createview),
#    url(r'^restaurant/(?P<slug>\w+)/$', Restaurantlistview.as_view()),
#    url(r'^restaurant/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name ="/restaurant-detail/"),
#    url(r'^restaurant/italijanska/$', Italijanskarestaurantlistview.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name ='about.html'), name= "about"),
    url(r'^contact/$', TemplateView.as_view(template_name ='contact.html'), name= "contact"),
]

cfehome/src/menus/urls.py
from django.conf.urls import url
from .views import ItemCreateView, ItemDetailView, ItemListView, ItemUpdateView

urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(), name= "create"),
#    url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name ="detail"),
    url(r'^$', ItemListView.as_view(), name= "list"),

]

cfehome/src/menus/models.py
from django.db import models
from django.conf import settings
from restaurant.models import RestaurantLocation
from django.core.urlresolvers import reverse


class Item(models.Model):
    #assosiation
    user =      models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant =models.ForeignKey(RestaurantLocation)
    #real item staf
    name =      models.CharField(max_length=120)
    contents =  models.TextField(help_text= "Separate by comma")
    excludes = models.TextField(blank=True, null= True,help_text="Separate by comma")
    public =    models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta():
        ordering = ["-update","-timestamp"]
    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={"pk":self.pk})
    def get_contents(self):
        return self.contents.split(",")
    def get_excludes(self):
        return self.excludes.split(",")




# Create your models here.

cfehome/src/menus/forms.py
from django import forms
from .models import Item
from restaurant.models import RestaurantLocation

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            "restaurant",
            "name",
            "contents",
            "public",
            "excludes"
        ]
    def __init__(self,user = None, *args, **kwargs):
        print(user)
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner = user)#exlude(item__isnull=False)

cfehome/src/menus/views.py
from django.shortcuts import render
from .models import Item
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from .forms import ItemForm
from django.contrib.auth.mixins import LoginRequiredMixin


class ItemListView(ListView):
    def get_queryset(self):
        return Item.objects.filter(user = self.request.user)

class ItemDetailView(DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = ItemForm
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)
    def get_context_data(self, **kwargs):
        context = super(ItemCreateView, self).get_context_data(**kwargs)
        context['title']= 'Creating Item'
        return context
    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'menus/menus_update.html'
    form_class = ItemForm
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)
    def get_context_data(self, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(**kwargs)
        context['title']= 'Update view'
        return context
    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

# Create your views here.

cfehome/src/menus/templates/menus/item_detail.html
{% extends "base.html"%}

{%block head_title%}Restaurant |{{ block.super }}{%endblock head_title%}
{% block content%}
<h1>{{object.name}}</h1>
<h1>Location :{{object.restaurant.name}}</h1>

<ul>
    {% for item in object.get_contents%}
    <li>{{ item }}</li>
    {% endfor%}
</ul>
<ul>
        {%if object.contents%}
              Exludes:
        <ul>
             {% for item in object.get_excludes%}
            <li>{{ item }}</li>
         {% endfor%}
            {%endif%}
        </ul>
</ul>


{% endblock content%}<h1>Location :{{object.restaurant.name}}</h1>

cfehome/src/menus/templates/menus/item_list.html
{% extends "base.html"%}

{%block head_title%}Restaurant |{{ block.super }}{%endblock head_title%}
{% block content%}
<h1>Menu item list<small><a href="{% url "menus:create" %}">Add</a></small></h1>
<ul>
    {% for obj in object_list %}
    <li>
        <a href='{{obj.get_absolute_url}}'>{{ obj.name }}></a><br>

        {%if obj.contents%}
        Contents:
        <ul>
             {% for item in obj.get_contents%}
            <li>{{ item }}</li>
            {% endfor%}
        {%endif%}
        {%if obj.contents%}
              Exludes:

             {% for item in obj.get_excludes%}
            <li>{{ item }}</li>
         {% endfor%}
        {%endif%}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock content%}

cfehome/src/menus/templates/menus/menus_update.html
{% extends "base.html"%}

{%block head_title%}{{form.instance.name}} |{{ block.super }}{%endblock head_title%}
{% block content%}
<h1>{{form.instance.name}}</h1>
<h1>Location :{{form.instance.restaurant.name}}</h1>

<ul>
    {% for item in form.instance.get_contents%}
    <li>{{ item }}</li>
    {% endfor%}
</ul>
<ul>
        {%if form.instance.contents%}
              Exludes:
        <ul>
             {% for item in form.instance.get_excludes%}
            <li>{{ item }}</li>
         {% endfor%}
            {%endif%}
        </ul>
</ul>
<h3>Make changes</h3>
{% include "snippets/form_snippet.html" with form=form %}

{% endblock content%}